# $File: //member/autrijus/cpanplus/dist/lib/CPANPLUS/FAQ.pod $
# $Revision: #3 $ $Change: 3564 $ $DateTime: 2002/03/27 05:03:47 $

=head1 NAME

CPANPLUS::FAQ - Frequently Asked Questions about CPANPLUS

=head1 DESCRIPTION

This is the Frequently Asked Questions list for the CPANPLUS kit.
More accurately, it's a very thin placeholder for where the FAQ will
soon be.

=head1 QUESTIONS

=head2 Can CPANPLUS do I<random something>?

If it has to do with installing modules, most likely! Keep in mind that
while the default shell may not be able to do something like "install all
modules in the POE namespace", you can easily make something of the sort,
using L<CPANPLUS::Backend>. 

=head2 Why not make I<some change> to the default shell?

The default shell is designed to be what the developers wanted in a shell.

If it doesn't do what you want, consider writing your own with
L<CPANPLUS::Backend>, and possibly releasing it in the B<CPANPLUS::Shell::*>
namespace. You can also change your default shell to be any other CPANPLUS
shell you have installed. 

=head2 What is the lowest version of Perl CPANPLUS works under?

Reliably under 5.005_03, but 5.004 is a theoretical possibility. 

=head2 On what platforms has CPANPLUS been tested?

FreeBSD, Linux, Win32 and Cygwin. 

=head2 How much CPANPLUS.pm code comes from CPAN.pm?

None.

=head2 How can I install modules if I'm not root?

Set C<makemakerflags> to something like this:

    LIB=~/perl/lib INSTALLMAN1DIR=~/perl/man/man1 INSTALLMAN3DIR=~/perl/man/man3 

Of course you should replace 'perl' with the appropriate directory.

Also, be sure never to use UNINST=1 in C<makeflags>.

=head2 Can I let different users on my system use CPANPLUS?

Currently, it is not possible to have multiple setup files, so all
users will use the same repository and configuration.

=head2 Can I use a local mirror (such as a CD), but fall back to a public mirror if my files are out of date?

To do this you need to ensure that you have an up-to-date listing
of modules so that if the most recent version of a module isn't
found in the local mirror, CPANPLUS will try to get it from the
external mirror.

In your setup, list only complete mirrors.  This way you will get
a current listing from one of them when you start CPANPLUS.

Next, add your local mirror at runtime so that it becomes the new
first choice.

In this example a CD from another server on the network is added
(leave off the host argument if it is on the local machine):

   my $cb = new CPANPLUS::Backend;
   my $conf = $cb->configure_object;

   $conf->_set_ftp(urilist => [ {
      path   => '/mnt/cdrom',
      scheme => 'file',
      host   => '//server',
   }, @{ $conf->_get_ftp('urilist') } ]);

Thanks to Nick Clark for asking this at the 2002 German Perl Workshop.

=head1 AUTHOR

Ann Barcomb E<lt>kudra@cpan.orgE<gt>.

=head1 COPYRIGHT

The CPAN++ interface (of which this document is a part of) is
copyright (c) 2001, 2002 Jos Boumans E<lt>kane@cpan.orgE<gt>.
All rights reserved.

This library is free software;
you may redistribute and/or modify it under the same
terms as Perl itself.

=head1 SEE ALSO

L<CPANPLUS::Backend>, L<CPANPLUS::Shell::Default>, L<CPANPLUS>,
L<CPANPLUS::Configure>

=cut
